project_id = "vgobynwzjafeamxcfahl"

[functions.send-partnership-notification]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false
